version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: opsnow-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./opsnow-be
    container_name: opsnow-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      # Optional JVM opts
      JAVA_OPTS: -Xms256m -Xmx512m
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./opsnow-frontend
      args:
        REACT_APP_API_URL: http://localhost:8080/api
    container_name: opsnow-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
